spdockit ps module installation
SysKitTeam/docs-spconsultant pull request #5
Opened 2018-12-05 07:22 UTC by banJanko

2018-12-05 07:29 UTC, tosirovect2 commented on installation/powershell-module-installation.md
> +
na kraju svega bi dobro došao link koji vodi na create snapshots članak.

2018-12-05 07:30 UTC, tosirovect2 commented on installation/powershell-module-installation.md
> +1.	Once you’ve downloaded syskit.spdockit.ps.1.0.5.nupkg, extract the file to location of your choosing.
ova verzija modula će se mjenjat s vremenom. možda najbolje zamjenit ju s iksićima? ili nešto slično.

2018-12-06 10:14 UTC, imesaric commented on TOC.md
> +## [PowerShell Module Install/Uninstall Guide](powershell-module-installation.md)
skratiti naziv - npr. PowerShell Guide ili nešto tome slično ako imaš bolju ideju. i staviti ga ispod postojeća tri članka u TOC-u

2018-12-06 10:14 UTC, imesaric commented on installation/powershell-module-installation.md
> +description: This article explains how to install SPDocKit PowerShell Module.
how to install/uninstall

2018-12-06 10:15 UTC, imesaric commented on installation/powershell-module-installation.md
> +After acquiring PowerShell module from [PowerShell Gallery](https://www.powershellgallery.com/packages/SysKit.SPDocKit.PS/) or SysKit [Customers Web](https://my.syskit.com), module can be imported by
, **the** module can be imported...

2018-12-06 10:17 UTC, imesaric commented on installation/powershell-module-installation.md
> +1.	Once you’ve downloaded syskit.spdockit.ps.1.X.X.nupkg, extract the file to location of your choosing.
extract the file to **a** location of your choosing

2018-12-06 10:17 UTC, imesaric commented on installation/powershell-module-installation.md
> +If you wish to uninstall SysKit.SPDocKit PS module from server inside your client’s farm you can use the following command.
from **a** server inside..

2018-12-06 10:18 UTC, imesaric commented on installation/powershell-module-installation.md
> +Or you can manually delete SysKit.SPDocKit PS file from location you chose during installation.
from **the** location you chose..

2018-12-06 10:19 UTC, imesaric commented on installation/powershell-module-installation.md
> +SysKit.SPDocKit module update can be done using following command:
using **the** following command:

2018-12-06 10:19 UTC, imesaric commented on installation/powershell-module-installation.md
> +Update the SysKit.SPDocKit PS module:
ovo je viška jer je rečeno već u prošloj rečenici

2018-12-06 10:22 UTC, imesaric commented on installation/powershell-module-installation.md
> +
fali još jedan dio:
kada napraviš update modula i pokreneš snapshot, snapshot se odradi sa starim modulom (nažalost)
da bi powershell skužio da postoji novi, treba zatvoriti i ponovno otvoriti powershell
isprobaj to na 2019 serveru i uvjeri se da to tako radi + dopiši u članak kako misliš da bilo najjasnije end useru

2018-12-06 10:24 UTC, imesaric requested changes
A couple of changes needed, and some info missing.

2018-12-06 12:50 UTC, imesaric approved these changes

2018-12-06 13:06 UTC, imesaric approved these changes
Ready to merge

2018-12-06 13:09 UTC, merged